version: '3.9'

services:
  app:
    image: node:18-alpine
    container_name: app
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - PORT=${PORT}
    depends_on:
      - postgres
    networks:
      - docker-network
  
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - docker-network

volumes:
  node_modules:
  data:
networks:
  docker-network:
    driver: bridge