version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - docker-network

volumes:
  node_modules:
  data:
networks:
  docker-network:
    driver: bridge